/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModificarPerfil.java
 *
 * Created on Nov 25, 2011, 7:06:54 PM
 */
package Clases;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class ModificarPerfil extends javax.swing.JFrame {

    /** Creates new form ModificarPerfil */
    Perfil p;
    String email;
    public ModificarPerfil(String correo,int num) {
        email=correo;
        p=new Perfil(correo);
    /**    Object d=p.getDia();
        String di=d.toString();
        Object m=p.getMes();
        String me=m.toString();
        Object a=(p.getAnio());
        String an=a.toString();
        this.cmb_dia.setSelectedItem(di);
        this.cmb_mes.setSelectedItem(me);
        this.cmb_año.setSelectedItem(an);
        initComponents(); **/
        Object o=num;
        String n= o.toString();
        String r=""+n;
        System.out.println(r);
        this.txt_tel.setText(""+p.getTel());
        //this.cb_act.setSelected(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextField1 = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_dia = new javax.swing.JComboBox();
        cmb_mes = new javax.swing.JComboBox();
        cmb_año = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cb_act = new javax.swing.JCheckBox();
        cb_desa = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();

        jScrollPane1.setViewportView(jEditorPane1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Perfil");
        getContentPane().setLayout(null);
        getContentPane().add(txt_tel);
        txt_tel.setBounds(140, 90, 250, 20);

        jLabel2.setText("Telefono: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(31, 94, 49, 14);

        jToggleButton1.setText("Realizar Cambios");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(107, 248, 113, 23);

        jLabel3.setText("Fechade Nacimiento: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(31, 129, 103, 14);

        jLabel4.setText("Dia");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(152, 129, 15, 14);

        cmb_dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmb_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_diaActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_dia);
        cmb_dia.setBounds(171, 126, 37, 20);

        cmb_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        getContentPane().add(cmb_mes);
        cmb_mes.setBounds(257, 126, 37, 20);

        cmb_año.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", " " }));
        getContentPane().add(cmb_año);
        cmb_año.setBounds(336, 126, 49, 20);

        jLabel5.setText("Mes");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 129, 19, 14);

        jLabel6.setText("Año");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(298, 129, 19, 14);

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18));
        jLabel7.setText("Modificar Perfil");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(152, 25, 172, 25);

        jButton1.setText("Volver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(254, 248, 63, 23);

        jLabel8.setText("Estado de Cuenta:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(31, 170, 90, 14);

        cb_act.setBackground(new java.awt.Color(153, 153, 153));
        cb_act.setText("Activada");
        cb_act.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_actMouseClicked(evt);
            }
        });
        getContentPane().add(cb_act);
        cb_act.setBounds(31, 191, 67, 23);

        cb_desa.setBackground(new java.awt.Color(153, 153, 153));
        cb_desa.setText("Desactivada");
        cb_desa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_desaMouseClicked(evt);
            }
        });
        getContentPane().add(cb_desa);
        cb_desa.setBounds(31, 217, 85, 23);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 490, 340);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-503)/2, (screenSize.height-371)/2, 503, 371);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_diaActionPerformed
        
    }//GEN-LAST:event_cmb_diaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();
        Profile pr=new Profile(email);
        pr.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        String tel=this.txt_tel.getText();
        int t=Integer.parseInt(tel);
        String dia=(String) this.cmb_dia.getSelectedItem();
        String mes=(String) this.cmb_mes.getSelectedItem();
        String anio=(String) this.cmb_año.getSelectedItem();
        int d=Integer.parseInt(dia);
        int m=Integer.parseInt(mes);
        int a=Integer.parseInt(anio);
        Date fe=new Date(a,m,d);
        p.modificarPerfil( t, fe);
        JOptionPane.showMessageDialog(null,"Perfil Modificado.");
        dispose();
        Profile pr=new Profile(email);
        pr.setVisible(true);
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void cb_actMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_actMouseClicked
        cb_act.setSelected(true);
        cb_desa.setSelected(false);
    }//GEN-LAST:event_cb_actMouseClicked

    private void cb_desaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_desaMouseClicked
        cb_act.setSelected(false);
        cb_desa.setSelected(true);
    }//GEN-LAST:event_cb_desaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ModificarPerfil("prueba3",6).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cb_act;
    private javax.swing.JCheckBox cb_desa;
    private javax.swing.JComboBox cmb_año;
    private javax.swing.JComboBox cmb_dia;
    private javax.swing.JComboBox cmb_mes;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextPane txt_tel;
    // End of variables declaration//GEN-END:variables
}
