/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModPerfil.java
 *
 * Created on Nov 29, 2011, 7:06:12 PM
 */
package Clases;

import java.lang.Object;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class ModPerfil extends javax.swing.JFrame {

    /** Creates new form ModPerfil */
     Perfil p;
    String email;
    public ModPerfil(String correo) {
        initComponents();
        email=correo;
        p=new Perfil(correo);
        Object d=p.getDia();
        String di=d.toString();
        Object m=p.getMes();
        String me=m.toString();
        Object a=(p.getAnio());
        String an=a.toString();
        this.cmb_dia.setSelectedItem(di);
        this.cmb_mes.setSelectedItem(me);
        this.cmb_año.setSelectedItem(an);
        initComponents(); 
        Object o=p.getTel();
        String n= o.toString();
        System.out.println(n);
        String r=""+n;
        this.txt_tel.setText(r);
        this.cb_act.setSelected(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmb_dia = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmb_mes = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmb_año = new javax.swing.JComboBox();
        cb_act = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cb_desa = new javax.swing.JCheckBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        jVolver = new javax.swing.JButton();
        txt_tel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel7.setText("Modificar Perfil");

        jLabel2.setText("Telefono: ");

        jLabel3.setText("Fechade Nacimiento: ");

        cmb_dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmb_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_diaActionPerformed(evt);
            }
        });

        jLabel4.setText("Dia");

        jLabel5.setText("Mes");

        cmb_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));

        jLabel6.setText("Año");

        cmb_año.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", " " }));

        cb_act.setBackground(new java.awt.Color(255, 255, 255));
        cb_act.setText("Activada");
        cb_act.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_actMouseClicked(evt);
            }
        });

        jLabel8.setText("Estado de Cuenta:");

        cb_desa.setBackground(new java.awt.Color(255, 255, 255));
        cb_desa.setText("Desactivada");
        cb_desa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_desaMouseClicked(evt);
            }
        });

        jToggleButton1.setText("Realizar Cambios");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        jVolver.setText("Volver");
        jVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVolverMouseClicked(evt);
            }
        });
        jVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cb_act)
                            .addComponent(cb_desa)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel2))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmb_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmb_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel6)
                                        .addGap(19, 19, 19)
                                        .addComponent(cmb_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(76, 173, Short.MAX_VALUE)
                    .addComponent(jToggleButton1)
                    .addGap(34, 34, 34)
                    .addComponent(jVolver)
                    .addGap(73, 171, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(cmb_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(cmb_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(cmb_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(cb_act)
                .addGap(3, 3, 3)
                .addComponent(cb_desa)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(270, 270, 270)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jToggleButton1)
                        .addComponent(jVolver))
                    .addGap(0, 47, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_diaActionPerformed
        
}//GEN-LAST:event_cmb_diaActionPerformed

    private void cb_actMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_actMouseClicked
        this.cb_act.setSelected(true);
        this.cb_desa.setSelected(false);
}//GEN-LAST:event_cb_actMouseClicked

    private void cb_desaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_desaMouseClicked
        cb_act.setSelected(false);
        cb_desa.setSelected(true);
}//GEN-LAST:event_cb_desaMouseClicked

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        String tel=this.txt_tel.getText();
        int t=Integer.parseInt(tel);
        String dia=(String) this.cmb_dia.getSelectedItem();
        String mes=(String) this.cmb_mes.getSelectedItem();
        String anio=(String) this.cmb_año.getSelectedItem();
        int d=Integer.parseInt(dia);
        int m=Integer.parseInt(mes);
        int a=Integer.parseInt(anio)-1900;
        Date fe=new Date(a,m,d);
        p.modificarPerfil( t, fe);
        JOptionPane.showMessageDialog(null,"Perfil Modificado.");
        dispose();
        Profile pr=new Profile(email);
        pr.setVisible(true);
}//GEN-LAST:event_jToggleButton1MouseClicked

    private void jVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVolverMouseClicked
        dispose();
        Profile pr=new Profile(email);
        pr.setVisible(true);
}//GEN-LAST:event_jVolverMouseClicked

    private void jVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolverActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ModPerfil("prueba4").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb_act;
    private javax.swing.JCheckBox cb_desa;
    private javax.swing.JComboBox cmb_año;
    private javax.swing.JComboBox cmb_dia;
    private javax.swing.JComboBox cmb_mes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jVolver;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
