/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Profile.java
 *
 * Created on Nov 22, 2011, 3:29:53 PM
 */
package Clases;

import java.awt.Image;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class Profile extends javax.swing.JFrame {

    /** Creates new form Profile */
    Perfil p;
    Posts po;
    String email;
    ImageIcon fotoP;
    public Profile(String correo) {
        this.email=correo;
        int cont=0;
        initComponents();
        p=new Perfil(correo);
        po=new Posts(correo);
        Calendar c=Calendar.getInstance();
        c.setTime(new Date(p.getFechaNacimiento()));
        
        
        this.jTextPane1.setText("Fecha de Nacimiento: \n"+p.fecha(c) +"\n\n"+
                                "Telefono: "+p.getTel()+"\n\n"+
                                "Correo: "+p.getEmail()+"\n\n"+
                                "Genero: "+p.getGenero());
        this.jLabelNombre.setText(p.getNombre());
        this.txt_posts.setText(po.getPosts());
       // if(!p.getFoto().equals("")){
            
           // this.jFotoPerfil.setIcon(setFoto(p.getFoto()));
       // }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bot_fotoperfil = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jFotoPerfil = new javax.swing.JLabel();
        txt_aPost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bot_agregarPost = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_posts = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bot_cerrarS = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bot_fotoperfil.setText("Cambiar Foto");
        bot_fotoperfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot_fotoperfilMouseClicked(evt);
            }
        });
        bot_fotoperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_fotoperfilActionPerformed(evt);
            }
        });

        jLabelNombre.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNombre.setFont(new java.awt.Font("Ravie", 2, 20));

        jFotoPerfil.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel2.setText("Nuevo Post");

        bot_agregarPost.setText("Agregar Post");
        bot_agregarPost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot_agregarPostMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bot_agregarPostMouseEntered(evt);
            }
        });

        txt_posts.setColumns(20);
        txt_posts.setEditable(false);
        txt_posts.setRows(5);
        jScrollPane3.setViewportView(txt_posts);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel3.setText("Amigos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel1.setText("Informacion Personal");

        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("Modificar Perfil");
        jButton1.setActionCommand("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver Solicitudes de Amistad");

        jButton3.setText("Buscar Amigo");

        bot_cerrarS.setText("Cerrar Sesion");
        bot_cerrarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot_cerrarSMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel4.setText("Posts Mas Recientes.");

        jButton4.setText("Regresar Al Inicio");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(bot_fotoperfil))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel2))
                                    .addComponent(bot_agregarPost, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_aPost, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(222, 222, 222))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)
                        .addComponent(bot_cerrarS)
                        .addComponent(jButton4)))
                .addGap(154, 154, 154))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(1045, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bot_fotoperfil)
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_aPost, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bot_agregarPost))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bot_cerrarS)
                        .addGap(273, 273, 273))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1105)/2, (screenSize.height-756)/2, 1105, 756);
    }// </editor-fold>//GEN-END:initComponents

    private void bot_fotoperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_fotoperfilActionPerformed
        
    }//GEN-LAST:event_bot_fotoperfilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bot_fotoperfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_fotoperfilMouseClicked
       ImageIcon foto= this.getFoto();

        if ( foto!= null){
            this.jFotoPerfil.setIcon(foto);

        }
    }//GEN-LAST:event_bot_fotoperfilMouseClicked

    private void bot_cerrarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_cerrarSMouseClicked
        LogIn l=new LogIn();
        dispose();
        l.setVisible(true);
        
    }//GEN-LAST:event_bot_cerrarSMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        ModPerfil m=new ModPerfil(email);
        dispose();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void bot_agregarPostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_agregarPostMouseClicked

        Calendar c=Calendar.getInstance();
        String e=this.txt_aPost.getText()+"\t\t Posteado a las: "+c.get(Calendar.HOUR)+":"+c.get(Calendar.MINUTE)+" "+(c.get(Calendar.AM_PM)==1 ? "PM" : "AM")+"\n\n";
        po.agregarPost(e);
        po.agegarPostInicio(p.getNombre(), e);
        this.txt_posts.setText(po.getPosts());
        //this.txt_posts.append(this.txt_aPost.getText()+"\t\t Posteado a las: "+c.get(Calendar.HOUR)+":"+c.get(Calendar.MINUTE)+"\n\n"+po.getPosts());

        JOptionPane.showMessageDialog(null, "Post Agregado.");
        this.txt_aPost.setText("");
    }//GEN-LAST:event_bot_agregarPostMouseClicked

    private void bot_agregarPostMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_agregarPostMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bot_agregarPostMouseEntered

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        HomeFeed home=new HomeFeed(p.getEmail());
        dispose();
        home.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Profile("prueba4").setVisible(true);
            }
        });
    }
        private ImageIcon getFoto() {
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Foto de Perfil");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int opcion = chooser.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION){

            String fotoPath = chooser.getSelectedFile().getAbsolutePath();
            p.guardarFoto(fotoPath);
            ImageIcon foto= new ImageIcon(fotoPath);

            ImageIcon fotoReal1= new ImageIcon(foto.getImage().getScaledInstance(this.jFotoPerfil.getWidth(), this.jFotoPerfil.getHeight(), Image.SCALE_DEFAULT));

            return fotoReal1;
        }
        return null;
    }
        private ImageIcon setFoto(String d){
            ImageIcon foto= new ImageIcon(d);

            ImageIcon fotoReal1= new ImageIcon(foto.getImage().getScaledInstance(this.jFotoPerfil.getWidth(), this.jFotoPerfil.getHeight(), Image.SCALE_DEFAULT));

            return fotoReal1;
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_agregarPost;
    private javax.swing.JToggleButton bot_cerrarS;
    private javax.swing.JButton bot_fotoperfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jFotoPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txt_aPost;
    private javax.swing.JTextArea txt_posts;
    // End of variables declaration//GEN-END:variables
}

